### PR TITLE
Changed text colour and separated alumni by year

### PR DESCRIPTION
**Pull request by ujjawaljaiswal2017**

### CODE REVIEW

**Comment by sanketsingh24** [comment]
I think all the photos should have the same style? (Prabodh Sir's is horizontal

**Comment by ujjawaljaiswal2017** [comment]
> I think all the photos should have the same style? (Prabodh Sir's is horizontal

It is because of the orientation of the original image

**Comment by sanketsingh24** [comment]
But it looks odd being the only horizontal icon

**Comment by ujjawaljaiswal2017** [comment]
> But it looks odd being the only horizontal icon

Okay I will crop the said image

**Pull request merged**
