### PR TITLE
Added folders to keep structure

### LINKED ISSUE #9: Adding proper structure to project
**Is your feature request related to a problem? Please describe.**
Every Project must have proper structure. It keeps the files organized.

**Describe the solution you'd like**
Will do it. Every page should be a module, with a views folder and a component folder. Component folder should contain small components and views folder should contain the final rendering component of the page. Menu Panel and Footer will remain same in all pages, so they can be in outer component folder, and can be included from there. Please comment if there's a confusion.

### PR DESCRIPTION
**Pull request by sanketsingh24**
Remove .keep files when adding real files there. Also, I have made 'some' module pages and not 'all' as an example. Fixes #9

### CODE REVIEW

**Comment by nveenjain** [comment]
What is significance of ./src/components?

**Comment by sanketsingh24** [comment]
That is for components common throughout multiple pages

**Comment by nveenjain** [comment]
Then, can't we rename the module folder to "pages", which looks more intuitive?

**Comment by sanketsingh24** [comment]
Well, definitely you can do so, but its just a folder, and shouldn't be a subject for attention and time (particularly yours).

**Pull request merged**
